server:
  port: 8080
  contextPath: /web3auth

logging:
  level:
    net.consensys.web3auth: ${LOG_LEVEL:INFO}

ethereum:
  enable: true
  node:
    url: ${ETHEREUM_RPC:http://localhost:8545}
    
    
web3-auth:      
  apps:            
    - appId: demo
      jwtSetting:
        issuer: "demo"
        secret: "secret!"
        expiration: 2592000
      authoritySetting:
        enable: true
        smartContract: ${CONTRACT_ADDRESS:0xd0b8a3c5d18f66b82c9d883728ed8078757b4c2b}
        mode: GETTER

      clients:
        - clientId: demo_client
          type: BROWSER
          url: http://localhost:8081
          loginSetting:
            timeout: 60
            cookieSetting:
                path: "/"
                domain: "localhost"
                secure: false
                
        - clientId: demo_service
          type: BEARER
          url: http://localhost:8082
          loginSetting:
            timeout: 60
            cookieSetting:
                path: "/"
                domain: "localhost"
                secure: false