server:
  port: ${SERVER_PORT:8080}
#  servlet:
#    context-path: /web3auth

logging:
  level:
    net.consensys.web3auth: ${LOG_LEVEL:INFO}


web3auth:
  instance: demo
  serverUrl: http://localhost:8080

  otc:
    type: DB # IN_MEMORY | DB
    dictionnary: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
    length: 10
    prefix: "Log in to demo.io by signing this secret code: "
    expiration: 60 # seconds

  jwt:
    issuer: "demo"
    secret: "s3cret!"
    expiration: 2592000 # seconds

  cookie:
     path: "/"
     domain: "localhost"
     secure: false

  wallet:
    mode: DIRECT # DIRECT | RELAY
    #relay:
    #  endpoint: http://localhost:8080/relay
    direct:
      mnemonic: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      rpcUrl: http://localhost:8545
      proxyFactory: "" # if empty - web3auth will deploy it
      gnosisSafeMasterCopy: "" # if empty - web3auth will deploy it

  clients:
    - clientId: demo-spring-web
      type: BROWSER  # BROWSER | BEARER
      defaultRedirect: http://localhost:8081
    - clientId: demo-react
      type: BROWSER  # BROWSER | BEARER
      defaultRedirect: http://localhost:3000
    - clientId: demo-api
      type: BEARER

  socialConnect:
    github:
      clientId:
      clientSecret: 

  cors:
    origins: "${CORS_ORIGIN:http://localhost.*}"
    methods: "${CORS_METHODS:GET,POST,PUT,OPTIONS,DELETE,PATCH}"
    headers: "${CORS_HEADERS:Access-Control-Allow-Headers,Origin,X-Requested-With,Content-Type,Accept,X-Auth-Token}"
    credentials: "${CORS_CREDENTIALS:true}"

  mongodb:
    host: ${SPRING_DATA_MONGODB_HOST:localhost}
    port: ${SPRING_DATA_MONGODB_PORT:27017}
    uri: ${SPRING_DATA_MONGODB_URI:#{null}}
    database: ${SPRING_DATA_MONGODB_DATABASE:web3auth}

#  authority:
#    mode: NONE # NONE | GETTER | EVENT | CACHE
#    ethereum: http://localhost:8545 # only for mode GETTER and EVENT
#    smartContract: 0x752dad129739df65e5a8949e50a63d231fbe8403 # only for mode GETTER and EVENT
#    kafkaAddress: localhost:9092 # only for mode CACHE
#    groupId: web3auth # only for mode CACHE
#    topic: contract-events # only for mode CACHE
