version: '3.2'
services:

  web3-auth:
    build: ./
    image: kauri/web3-auth
    ports:
    - "8080:8080"
    environment:
      LOG_LEVEL: TRACE
      WEB3AUTH_CONF: classpath:/application.yml
      ETHEREUM_RPC: http://ganache:8545
    depends_on:
      - ganache
    networks:
      - default
      
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    volumes:
      - .ethereum_data:/ethereum_data
    entrypoint:
      - node
      - ./build/cli.node.js
      - --host=0.0.0.0
      - --port=8545
      - --secure -u 0 -u 1
    networks:
      - default


networks:
  default:
