version: '3.2'
services:

  web3auth:
    build: ./
    image: kauriorg/web3auth
    ports:
    - "8080:8080"
    environment:
      LOG_LEVEL: TRACE
      WEB3AUTH_CONF: classpath:/application.yml
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_RPC: wss://rinkeby.infura.io/ws
    depends_on:
      - truffle
    links:
      - truffle
    command: >
      /bin/sh -c '
        echo Waiting for contract to be deployed...;
        while ! nc -z truffle 8888;
        do
          sleep 1;
        done;
        result=$$(curl http://truffle:8888/api/Community | jq -r .address)
        export CONTRACT_ADDRESS=$$result
        echo CONTRACT_ADDRESS=$$CONTRACT_ADDRESS
        echo Starting app...
        java -jar app.jar
      '
    networks:
      - default
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - default
      
  truffle:
    image: gjeanmart/truffle-docker
    ports:
      - "8888:8888"
    volumes:
      - /home/gjeanmart/workspace/kauri/prague/smart-contracts:/project
    environment:
      ACTION: migrate
      NETWORK: rinkeby
      API_PORT: 8888
      API_HOST: 0.0.0.0
    networks:
      - default


networks:
  default:
