version: '3.2'
services:

  web3auth:
    build: ./
    image: kauriorg/web3auth:snapshot
    ports:
    - "8080:8080"
    environment:
      LOG_LEVEL: TRACE
      WEB3AUTH_CONF: classpath:/application.yml
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_RPC: http://eth-node:8545
    depends_on:
      - truffle
    links:
      - truffle
    command: >
      /bin/sh -c '
        echo Waiting for contract to be deployed...;
        while ! nc -z truffle 8888;
        do
          sleep 1;
        done;
        result=$$(curl http://truffle:8888/api/Community | jq -r .address)
        export CONTRACT_ADDRESS=$$result
        echo CONTRACT_ADDRESS=$$CONTRACT_ADDRESS
        echo Starting app...
        java -jar app.jar
      '
    networks:
      - default
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - default
      
  eth-node:
    image: gjeanmart/parity-dev-docker
    ports:
      - "8545:8545"
    volumes:
      - .ethereum_data:/root/.local/share/io.parity.ethereum
      - .ethereum_log:/data/parity-logs
    environment:
      AMOUNT: 10
      ACCOUNTS: 0xf0f15cedc719b5a55470877b0710d5c7816916b1,0x31b26E43651e9371C88aF3D36c14CfD938BaF4Fd
    networks:
      - default


  truffle:
    image: gjeanmart/truffle-docker:latest
    ports:
      - "8888:8888"    
    volumes:
      - ${GITHUB_SSH_PRIVATE_KEY}:/root/.ssh/id_rsa
      - ${GITHUB_SSH_PUBLIC_KEY}:/root/.ssh/id_rsa.pub
    depends_on:
      - eth-node
    environment:
      GIT_URL: git@github.com:kauri-io/kauri-smart-contracts.git
      GIT_BRANCH: dev2
      NETWORK: docker
      API_PORT: 8888
      API_HOST: 0.0.0.0
    networks:
      - default


networks:
  default:
